#!/usr/bin/env bash
#Displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
w=1
while  [ $w -lt 11 ]
do
    if [ $w = 9 ]
    then
    echo "Hi"
else
    echo "Best School"
    fi
    let w+=1
done
