#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and:
i=1
while [ $i -lt 11 ]
  do
  if [ $i = 4 ]
  then
#displays bad luck for the 4th loop iteration
  echo "bad luck"
  elif [ $i = 8 ]
  then
#displays good luck for the 8th loop iteration
  echo "good luck"
  else
#displays Best School for the other iterations
  echo "Best School"
  fi
  (( i++ ))
done
