#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 20 and:
num=1
while [ $num -lt 21 ]
do
  case $num in
  4)
#displays 4 and then bad luck from China for the 4th loop iteration
    echo $num
    echo "bad luck from China" ;;
   9)
#displays 9 and then bad luck from Japan for the 9th loop iteration
    echo $num
    echo "bad luck from Japan" ;;
  17)
#displays 17 and then bad luck from Italy for the 17th loop iteration
    echo $num
    echo "bad luck from Italy" ;;
  *)
    echo $num ;;
  esac
  (( num++ ))
done
