#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:
h=0
#display hours from 0 to 12
while [ $h -le 12 ];
do
m=1
#display minutes from 1 to 59
  echo "Hour: $h"
  while [ $m -lt 60 ];
  do
    echo $m
    m=$(( m+=1))
done
h=$(( h+=1 ))
done
